name: Convert Rules to Clash Format

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  push:
    paths:
      - 'lucere30/MR/lq/*.list'
      - 'lucere30/MR/lq/*.txt'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          pwd
          ls -la
          echo "MR directory contents (if exists):"
          ls -la MR || echo "MR directory not found"
          echo "lucere30/MR/lq directory contents (if exists):"
          ls -la lucere30/MR/lq || echo "lucere30/MR/lq directory not found"

      - name: Convert rules to Clash format
        run: |
          # 确保输出目录存在
          mkdir -p MR/cat
          
          # 初始化转换标志
          CONVERTED=false
          
          # 检查源文件目录是否存在
          if [ ! -d "lucere30/MR/lq" ]; then
            echo "Error: Source directory lucere30/MR/lq does not exist"
            exit 1
          fi
          
          # 检查是否有源文件
          shopt -s nullglob
          files=(lucere30/MR/lq/*.{list,txt})
          if [ ${#files[@]} -eq 0 ]; then
            echo "No .list or .txt files found in lucere30/MR/lq/"
            exit 0
          fi
          
          # 处理每个文件
          for file in "${files[@]}"; do
            echo "Processing file: $file"
            
            # 获取文件名（不含扩展名）
            filename=$(basename "$file" | sed 's/\.[^.]*$//')
            
            # 创建输出文件
            output_file="MR/cat/${filename}.yaml"
            
            # 写入 yaml 头部
            echo "payload:" > "$output_file"
            
            # 处理文件内容
            while IFS= read -r line || [ -n "$line" ]; do
              # 跳过空行和注释行
              [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
              
              # 移除可能存在的回车符并去除前后空格
              line=$(echo "$line" | tr -d '\r' | awk '{$1=$1};1')
              
              # 写入规则
              echo "  - $line" >> "$output_file"
            done < "$file"
            
            echo "Created file: $output_file"
            CONVERTED=true
          done
          
          # 检查是否有生成的文件
          if [ "$CONVERTED" = true ]; then
            echo "Conversion completed successfully"
            echo "Generated files in MR/cat/:"
            ls -la MR/cat/
          else
            echo "No files were converted"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          # 检查是否有 yaml 文件
          if [ -n "$(find MR/cat -maxdepth 1 -name '*.yaml' -print -quit)" ]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            
            # 使用 find 命令添加文件
            find MR/cat -name "*.yaml" -exec git add {} \;
            
            # 检查是否有改动
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "chore: Convert rules to Clash format"
              git push
            fi
          else
            echo "No yaml files found in MR/cat/"
            exit 1
          fi
