name: Convert Rules to Clash Format

on:
  push:
    paths:
      - 'MR/lq/*.list'
      - 'MR/lq/*.txt'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Convert rules to Clash format
        run: |
          # 创建输出目录
          mkdir -p MR/cat

          # 处理 MR/lq 目录下的所有 .list 和 .txt 文件
          for file in MR/lq/*.{list,txt}; do
            # 检查文件是否存在
            [ -f "$file" ] || continue
            
            # 获取文件名（不含扩展名）
            filename=$(basename "$file" | sed 's/\.[^.]*$//')
            
            # 创建输出文件
            output_file="MR/cat/${filename}.yaml"
            
            # 写入 yaml 头部
            echo "payload:" > "$output_file"
            
            # 处理每一行规则并转换格式
            while IFS= read -r line || [[ -n "$line" ]]; do
              # 跳过空行和注释行
              [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
              
              # 移除可能存在的回车符并去除前后空格
              line=$(echo "$line" | tr -d '\r' | awk '{$1=$1};1')
              
              # 直接写入规则，保持原始格式
              echo "  - ${line}" >> "$output_file"
            done < "$file"
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add MR/cat/*.yaml
          git commit -m "chore: Convert rules to Clash format" || echo "No changes to commit"
          git push