name: Convert Rules to Clash Format

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  push:
    paths:
      - 'MR/lq/*.list'
      - 'MR/lq/*.txt'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert rules to Clash format
        run: |
          # 确保输出目录存在
          mkdir -p MR/cat
          
          # 处理所有 .list 和 .txt 文件
          for file in MR/lq/*.{list,txt}; do
            # 检查文件是否存在（防止没有匹配文件时的错误）
            [ -e "$file" ] || continue
            
            # 获取文件名（不含扩展名）
            filename=$(basename "$file" | sed 's/\.[^.]*$//')
            
            # 创建输出文件
            output_file="MR/cat/${filename}.yaml"
            
            # 写入 yaml 头部
            echo "payload:" > "$output_file"
            
            # 处理文件内容
            sed -n '/^[^#]/p' "$file" | sed '/^$/d' | sed 's/^/  - /' >> "$output_file"
          done

      - name: Check for changes
        id: check_changes
        run: |
          git add MR/cat/*.yaml
          git status --porcelain | grep "MR/cat/" > /dev/null
          echo "changed=$?" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 0
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: Convert rules to Clash format"
          git push
