name: Convert LQ Rules to Cat Format

on:
  schedule:
    - cron: "0 6 * * *" # 每天 06:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 确保源目录存在
        run: |
          mkdir -p MR/lq MR/cat

      - name: 转换规则格式
        run: |
          file_count=0
          for file in MR/lq/*.{list,txt}; do
            [ -f "$file" ] || continue
            filename=$(basename "$file")
            filename_no_ext="${filename%.*}"
            output_file="MR/cat/${filename_no_ext}.yaml"
            echo "payload:" > "$output_file"
            while IFS= read -r line; do
              [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
              echo "  - DOMAIN-SUFFIX,$line" >> "$output_file"
            done < "$file"
            file_count=$((file_count + 1))
          done
          if [ "$file_count" -eq 0 ]; then
            echo "No files found in MR/lq, skipping commit."
            exit 0
          fi

      - name: 检查转换后的文件
        run: |
          echo "Converted files:"
          ls -lah MR/cat/

      - name: 提交转换后的规则
        run: |
          if [ -n "$(ls -A MR/cat/)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add MR/cat/*.yaml
            git commit -m "自动转换 LQ 规则为 Cat 格式" || echo "No changes to commit"
            git push
          else
            echo "No YAML files to commit. Skipping git operations."
          fi
