name: Convert

on:
  schedule:
    - cron: "0 6 * * *" # 每天 06:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 确保源目录存在
        run: |
          mkdir -p MR/lq MR/cat

      - name: 转换规则格式
        run: |
          for file in MR/lq/*; do
            [ -f "$file" ] || continue
            filename=$(basename "$file")
            echo "payload:" > "MR/cat/${filename}.yaml"
            while IFS= read -r line; do
              [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
              echo "  - DOMAIN-SUFFIX,$line" >> "MR/cat/${filename}.yaml"
            done < "$file"
          done

      - name: 提交转换后的规则
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add MR/cat/*.yaml
          git commit -m "自动转换 LQ 规则为 Cat 格式" || echo "No changes to commit"
          git push
