name: Sync and Process ADLite

on:
  schedule:
    - cron: '0 20 * * *'  # 每天 20:00 自动运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-and-process:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2️⃣ 下载外部规则文件并命名为 adlite.list
      - name: Download rules file
        run: |
          wget https://raw.githubusercontent.com/deezertidal/private/refs/heads/main/rule/ADLite.list -O adlite.list

      # 3️⃣ 处理文件，在每行 IP 后添加 `,no-resolve`
      - name: Process file
        run: |
          python3 <<EOF
          import re
          with open("adlite.list", "r") as file:
              lines = file.readlines()
          processed_lines = [re.sub(r'(\d{1,3}(\.\d{1,3}){3}\/\d+)', r'\1,no-resolve', line) for line in lines]
          with open("adlite.list", "w") as file:
              file.writelines(processed_lines)
          EOF


      # 4️⃣ 提交并推送到 `main/lq` 文件夹
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          mkdir -p lq  # 确保 lq 目录存在
          mv adlite.list lq/  # 移动文件到 lq 目录
          git add lq/adlite.list  # 添加 lq 目录下的文件
          if ! git diff --cached --quiet; then
              git commit -m "Update adlite"
              git push origin HEAD:main
          fi
